Loading JSON data into dataframe

In [ ]:
import pandas as pd

brands_df = pd.read_json('brands.json', lines=True)
receipts_df = pd.read_json('receipts.json', lines=True)
users_df = pd.read_json('users.json', lines=True)

In [ ]:
brands_df.head()

0        True
1       False
2       False
3       False
4       False
        ...
1162     True
1163    False
1164    False
1165    False
1166    False
Name: brandCode, Length: 1167, dtype: bool

In [ ]:
users_df.head()

,_id,active,createdDate,lastLogin,role,signUpSource,state
0,{'$oid': '5ff1e194b6a9d73a3a9f1052'},True,{'$date': 1609687444800},{'$date': 1609687537858},consumer,Email,WI
1,{'$oid': '5ff1e194b6a9d73a3a9f1052'},True,{'$date': 1609687444800},{'$date': 1609687537858},consumer,Email,WI
2,{'$oid': '5ff1e194b6a9d73a3a9f1052'},True,{'$date': 1609687444800},{'$date': 1609687537858},consumer,Email,WI
3,{'$oid': '5ff1e1eacfcf6c399c274ae6'},True,{'$date': 1609687530554},{'$date': 1609687530597},consumer,Email,WI
4,{'$oid': '5ff1e194b6a9d73a3a9f1052'},True,{'$date': 1609687444800},{'$date': 1609687537858},consumer,Email,WI

In [ ]:
receipts_df

,_id,bonusPointsEarned,bonusPointsEarnedReason,createDate,dateScanned,finishedDate,modifyDate,pointsAwardedDate,pointsEarned,purchaseDate,purchasedItemCount,rewardsReceiptItemList,rewardsReceiptStatus,totalSpent,userId
0,{'$oid': '5ff1e1eb0a720f0523000575'},500.0,"Receipt number 2 completed, bonus point schedu...",{'$date': 1609687531000},{'$date': 1609687531000},{'$date': 1609687531000},{'$date': 1609687536000},{'$date': 1609687531000},500.0,{'$date': 1609632000000},5.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,26.00,5ff1e1eacfcf6c399c274ae6
1,{'$oid': '5ff1e1bb0a720f052300056b'},150.0,"Receipt number 5 completed, bonus point schedu...",{'$date': 1609687483000},{'$date': 1609687483000},{'$date': 1609687483000},{'$date': 1609687488000},{'$date': 1609687483000},150.0,{'$date': 1609601083000},2.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,11.00,5ff1e194b6a9d73a3a9f1052
2,{'$oid': '5ff1e1f10a720f052300057a'},5.0,All-receipts receipt bonus,{'$date': 1609687537000},{'$date': 1609687537000},NaN,{'$date': 1609687542000},NaN,5.0,{'$date': 1609632000000},1.0,"[{'needsFetchReview': False, 'partnerItemId': ...",REJECTED,10.00,5ff1e1f1cfcf6c399c274b0b
3,{'$oid': '5ff1e1ee0a7214ada100056f'},5.0,All-receipts receipt bonus,{'$date': 1609687534000},{'$date': 1609687534000},{'$date': 1609687534000},{'$date': 1609687539000},{'$date': 1609687534000},5.0,{'$date': 1609632000000},4.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,28.00,5ff1e1eacfcf6c399c274ae6
4,{'$oid': '5ff1e1d20a7214ada1000561'},5.0,All-receipts receipt bonus,{'$date': 1609687506000},{'$date': 1609687506000},{'$date': 1609687511000},{'$date': 1609687511000},{'$date': 1609687506000},5.0,{'$date': 1609601106000},2.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,1.00,5ff1e194b6a9d73a3a9f1052
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1114,{'$oid': '603cc0630a720fde100003e6'},25.0,COMPLETE_NONPARTNER_RECEIPT,{'$date': 1614594147000},{'$date': 1614594147000},NaN,{'$date': 1614594148000},NaN,25.0,{'$date': 1597622400000},2.0,"[{'barcode': 'B076FJ92M4', 'description': 'mue...",REJECTED,34.96,5fc961c3b8cfca11a077dd33
1115,{'$oid': '603d0b710a720fde1000042a'},NaN,NaN,{'$date': 1614613361873},{'$date': 1614613361873},NaN,{'$date': 1614613361873},NaN,NaN,NaN,NaN,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
1116,{'$oid': '603cf5290a720fde10000413'},NaN,NaN,{'$date': 1614607657664},{'$date': 1614607657664},NaN,{'$date': 1614607657664},NaN,NaN,NaN,NaN,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
1117,{'$oid': '603ce7100a7217c72c000405'},25.0,COMPLETE_NONPARTNER_RECEIPT,{'$date': 1614604048000},{'$date': 1614604048000},NaN,{'$date': 1614604049000},NaN,25.0,{'$date': 1597622400000},2.0,"[{'barcode': 'B076FJ92M4', 'description': 'mue...",REJECTED,34.96,5fc961c3b8cfca11a077dd33
1118,{'$oid': '603c4fea0a7217c72c000389'},NaN,NaN,{'$date': 1614565354962},{'$date': 1614565354962},NaN,{'$date': 1614565354962},NaN,NaN,NaN,NaN,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33

Checking `rewardsReceiptItemList` to identify a key to join **brands** table and **receipts** table

In [ ]:
receipts_df['rewardsReceiptItemList'][20]
receipts_df['rewardsReceiptItemList'][439]

In [ ]:

for j in range(1, len(receipts_df)):
    print('\n')
    item_list = receipts_df['rewardsReceiptItemList'][j]
    # Check if item_list is a list before proceeding.
    if isinstance(item_list, list):
        for i in range(len(item_list)):
            item = item_list[i]
            # Check if 'barcode' exists and item is a dictionary.
            if isinstance(item, dict) and 'barcode' in item:
                print(item['barcode'])

            else:
                print("Barcode not found for item at index", i)
    else:
        print("Item at index", j, "is not a list.")

Many items in the receipt have invalid barcode or barcode not found.

Checking if `brandCode` can be used to join receipts and brands table.

In [ ]:

for j in range(1, len(receipts_df)):
    print('\n')
    item_list = receipts_df['rewardsReceiptItemList'][j]
    # Check if item_list is a list before proceeding.
    if isinstance(item_list, list):
        for i in range(len(item_list)):
            item = item_list[i]
            # Check if 'barcode' exists and item is a dictionary.
            if isinstance(item, dict) and 'brandCode' in item:
                print(item['brandCode'])
            else:
                print("brandCode not found for item at index", i)
    else:
        print("Item at index", j, "is not a list.")

By checking multible value ranges of j, we can say that Many brandCode values are missing. Hence we can proceed with barcode for joining brands and receipt data as it has fewer missing values

**Checking `rewardsReceiptStatus` values to answer:**
 When considering average spend from receipts with 'rewardsReceiptStatus’ of ‘Accepted’ or ‘Rejected’, which is greater?

In [ ]:
receipts_df['rewardsReceiptStatus'].value_counts()

FINISHED     518
SUBMITTED    434
REJECTED      71
PENDING       50
FLAGGED       46
Name: rewardsReceiptStatus, dtype: int64

# Checking Uniquness of ids and nulls for keys

In [ ]:
receipts_df['_id'].value_counts()

{'$oid': '5ff1e1eb0a720f0523000575'}    1
{'$oid': '601b48df0a720f05f4000238'}    1
{'$oid': '601c11410a720f05f400028e'}    1
{'$oid': '601c2d630a7214ad280002a7'}    1
{'$oid': '601be7120a720f05f400027a'}    1
                                       ..
{'$oid': '60088a670a720f05fa0000e0'}    1
{'$oid': '600788cd0a7214ad8900003a'}    1
{'$oid': '60085bad0a720f05fa00006c'}    1
{'$oid': '60088e670a720f05fa00011d'}    1
{'$oid': '603c4fea0a7217c72c000389'}    1
Name: _id, Length: 1119, dtype: int64

In [ ]:
# Count of non-null values
non_null_count = receipts_df['brandCode'].notnull().sum()

# Count of null values
null_count = receipts_df['brandCode'].isnull().sum()

non_null_count, null_count

In [ ]:
brands_df['_id'].value_counts()

In [ ]:
# Count of non-null values
non_null_count = brands_df['brandCode'].notnull().sum()

# Count of null values
null_count = brands_df['brandCode'].isnull().sum()

non_null_count, null_count

(933, 234)

In [ ]:
# Count of non-null values
non_null_count = brands_df['barcode'].notnull().sum()

# Count of null values
null_count = brands_df['barcode'].isnull().sum()

non_null_count, null_count

(1167, 0)

In [ ]:
brands_df['topBrand'].value_counts()

0.0    524
1.0     31
Name: topBrand, dtype: int64

In [ ]:
users_df['_id'].value_counts()

{'$oid': '54943462e4b07e684157a532'}    20
{'$oid': '5fc961c3b8cfca11a077dd33'}    20
{'$oid': '5ff5d15aeb7c7d12096d91a2'}    18
{'$oid': '5fa41775898c7a11a6bcef3e'}    18
{'$oid': '59c124bae4b0299e55b0f330'}    18
                                        ..
{'$oid': '6004a965e257124ec6b9a39f'}     1
{'$oid': '600746fd6e64691717e8cfb5'}     1
{'$oid': '60074b996e64691717e8f11a'}     1
{'$oid': '60074246325c8a12289e22a0'}     1
{'$oid': '60088e5d633aab121bb8e5cf'}     1
Name: _id, Length: 212, dtype: int64


The inspection of the users reveals significant data quality issues, notably duplicate user records. Multiple entries have the same _id values, indicating repeated records for what should be unique user identifiers